### PR TITLE
bump version, dependencies to be able to use latest graphql features

### PR DESCRIPTION
**Pull request by karthage-spartacus**
Hello there,

just wanted to use the latest features, so I bumped `graphql` and `graphql-tag` to latest versions.

### CODE REVIEW

**Comment by karthage-spartacus** [comment]
Hey there,

Should I wait for the merge or push to an other atmosphere package ?
Is this repo still maintained ?

**Comment by jamiter** [comment]
@Cliffzz, could you have a look?

**Review by Cliffzz — CHANGES_REQUESTED** [review]
Please update the changelog as well.

**Review by Cliffzz — APPROVED** [review]

**Comment by Cliffzz** [comment]
@nathanschwarz New version has been published, thanks for the contribution 😄

**Pull request merged**
